// Copyright © 2020 Sovren Group, Inc. All rights reserved.
// This file is provided for use by, or on behalf of, Sovren licensees
// within the terms of their license of Sovren products or Sovren customers
// within the Terms of Service pertaining to the Sovren SaaS products.

using Sovren.Models.API.BimetricScoring;
using Sovren.Models.API.Geocoding;
using Sovren.Models.API.Matching.Request;
using Sovren.Models.API.Matching.Response;
using Sovren.Models.API.Parsing;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Sovren.Models.API.Matching.UI
{
    /// <inheritdoc/>
    public class UIMatchDetailsRequest : GenerateUIDetailsRequest<AIMatchDetails>
    {
        internal UIMatchDetailsRequest(AIMatchDetails details, UIOptions uiOptions) : base(details, uiOptions) { }
    }

    /// <inheritdoc/>
    public class UIBimetricScoreResumeDetailsRequest : GenerateUIDetailsRequest<BimetricScoreResumeDetails>
    {
        internal UIBimetricScoreResumeDetailsRequest(BimetricScoreResumeDetails details, UIOptions uiOptions) : base(details, uiOptions) { }
    }

    /// <inheritdoc/>
    public class UIBimetricScoreJobDetailsRequest : GenerateUIDetailsRequest<BimetricScoreJobDetails>
    {
        internal UIBimetricScoreJobDetailsRequest(BimetricScoreJobDetails details, UIOptions uiOptions) : base(details, uiOptions) { }
    }

    /// <summary>
    /// The request body for generating a Sovren Matching UI 'Details' session
    /// </summary>
    public class GenerateUIDetailsRequest<T> where T : MatchDetails
    {
        /// <summary>
        /// The information about the match result for this session. These properties should be filled from an AI Match or Bimetric Score API response.
        /// </summary>
        public T MatchDetails { get; set; }

        /// <summary>
        /// Various options for the Matching UI user experience
        /// </summary>
        public BasicUIOptions UIOptions { get; set; }

        internal GenerateUIDetailsRequest(T details, UIOptions uiOptions)
        {
            MatchDetails = details;
            UIOptions = BasicUIOptions.Create(uiOptions);
        }
    }

    /// <summary>
    /// Contains the data needed to generate a UI 'details' view
    /// </summary>
    public abstract class MatchDetails
    {
        /// <summary>
        /// The <see cref="CategoryWeights"/> object from the API call that generated the Result.
        /// </summary>
        public CategoryWeights AppliedCategoryWeights { get; set; }

        /// <summary>
        /// The HTML resume to be displayed in the details view. If you do not provide this, only the 
        /// plain text for the document is shown. The only allowed HTML string is the one generated by 
        /// Sovren (see <see cref="Conversions.HTML"/>) when you set <see cref="ParseOptions.OutputHtml"/> to true.
        /// </summary>
        public string HtmlDocument { get; set; }

        /// <summary>
        /// The type of document the result you are viewing was scored against
        /// </summary>
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public Models.Matching.IndexType SourceDocumentType { get; set; }
    }

    /// <summary>
    /// Contains the data needed to generate a UI 'details' view
    /// </summary>
    public class AIMatchDetails : MatchDetails
    {
        /// <summary>
        /// A single result from an AI Match query that you want to view in this details session
        /// </summary>
        public MatchResult Result { get; set; }
    }

    /// <summary>
    /// Contains the data needed to generate a UI 'details' view
    /// </summary>
    public abstract class BimetricScoreDetails : MatchDetails
    {
        /// <summary>
        /// A single result from a Bimetric Score API call that you want to view in this details session
        /// </summary>
        public BimetricScoreResult Result { get; set; }
    }

    /// <summary>
    /// Contains the data needed to generate a UI 'details' view
    /// </summary>
    public class BimetricScoreResumeDetails : BimetricScoreDetails
    {
        /// <summary>
        /// The parsed data to view in this session
        /// </summary>
        public Resume.ParsedResume ResumeData { get; set; }
    }

    /// <summary>
    /// Contains the data needed to generate a UI 'details' view
    /// </summary>
    public class BimetricScoreJobDetails : BimetricScoreDetails
    {
        /// <summary>
        /// The parsed data to view in this session
        /// </summary>
        public Job.ParsedJob JobData { get; set; }
    }
}
