name: build

on:
  pull_request:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          2.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/Textkernel.Tx.SDK
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/Textkernel.Tx.SDK

  unit-tests:
    runs-on: ubuntu-latest
    # only run this if we have already generated docfx in last commit
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create credentials file
      run: 'echo "$CREDENTIALS_FILE" > src/Textkernel.Tx.SDK.Tests/credentials.json'
      shell: bash
      env:
        CREDENTIALS_FILE: ${{secrets.TEST_CREDENTIALS}}
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/Textkernel.Tx.SDK.Tests
    - name: Build
      run: dotnet build
      working-directory: src/Textkernel.Tx.SDK.Tests
    - name: Test
      run: dotnet test
      working-directory: src/Textkernel.Tx.SDK.Tests