name: nuget-publish

on:
  release:
    types: [published]
  workflow_dispatch: #add this option in case of a failure and we need to re-run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          7.0.x
          2.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/Textkernel.Tx.SDK
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/Textkernel.Tx.SDK
    - name: Pack
      run: dotnet pack --no-build --configuration Release src/Textkernel.Tx.SDK/Textkernel.Tx.SDK.csproj --output .
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_API_KEY}}
      
