name: unit-tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Create credentials file
      run: 'echo "$CREDENTIALS_FILE" > src/Sovren.SDK.Tests/credentials.json'
      shell: bash
      env:
        CREDENTIALS_FILE: ${{secrets.TEST_CREDENTIALS}}
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/Sovren.SDK.Tests
    - name: Build
      run: dotnet build
      working-directory: src/Sovren.SDK.Tests
    - name: Test
      run: dotnet test
      working-directory: src/Sovren.SDK.Tests
